apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: ishaq786/fastapi
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: fastapi # Corrected this line to properly match the labels of the pods created by the deployment
